#include "LogCapture.h"

#include <sstream>
#if __has_include(<config.h>)

// Qt defines `signals` as a macro; SUMO headers use `signals` as an
// identifier.  Save / restore around the SUMO includes.
#pragma push_macro("signals")
#undef signals
// SUMO's OutputDevice.h pulls in <config.h> from the SUMO build tree.  It's
// generated by SUMO's CMake, so we look it up via the SUMO_HOME-derived
// build dir (cmclaude/src) which we add to the qt_cpp include path.
#include <config.h>
#include <utils/common/MsgHandler.h>
#include <utils/iodevices/OutputDevice.h>
#pragma pop_macro("signals")
namespace {


class LogCapture : public OutputDevice {
public:
    LogCapture(LogRouter* router, int level)
        : OutputDevice(/*defaultIndentation=*/0, /*filename=*/std::string{}),
          m_router(router), m_level(level) {}

    ~LogCapture() override {
        // MsgHandler stores raw pointers in three retriever lists.  Remove
        // ourselves from all of them so a stray inform() can't dereference us.
        MsgHandler::removeRetrieverFromAllInstances(this);
    }

protected:
    std::ostream& getOStream() override { return m_buf; }

    void postWriteHook() override {
        std::string s = m_buf.str();
        m_buf.str(std::string{});
        m_buf.clear();
        if (s.empty()) return;
        if (s.back() == '\n') s.pop_back();
        if (s.empty()) return;
        if (m_router) {
            // Same-thread invocation; the per-receiver connection type from
            // the connect() call carries the message across to the GUI thread.
            QMetaObject::invokeMethod(m_router, "logged", Qt::DirectConnection,
                                      Q_ARG(int, m_level),
                                      Q_ARG(QString, QString::fromStdString(s)));
        }
    }

private:
    std::ostringstream m_buf;
    LogRouter* m_router;
    int m_level;
};

}  // namespace

struct LogCaptureSet::Impl {
    std::unique_ptr<LogCapture> info;
    std::unique_ptr<LogCapture> warn;
    std::unique_ptr<LogCapture> err;
};

#endif

LogCaptureSet::LogCaptureSet() = default;
LogCaptureSet::~LogCaptureSet() = default;
LogCaptureSet::LogCaptureSet(LogCaptureSet&&) noexcept = default;
LogCaptureSet& LogCaptureSet::operator=(LogCaptureSet&&) noexcept = default;

LogCaptureSet installLogCaptures(LogRouter* router) {
    LogCaptureSet set;
#if __has_include(<config.h>)
    set.impl = std::make_unique<LogCaptureSet::Impl>();
    set.impl->info = std::make_unique<LogCapture>(router, 0);
    set.impl->warn = std::make_unique<LogCapture>(router, 1);
    set.impl->err  = std::make_unique<LogCapture>(router, 2);
    MsgHandler::getMessageInstance()->addRetriever(set.impl->info.get());
    MsgHandler::getWarningInstance()->addRetriever(set.impl->warn.get());
    MsgHandler::getErrorInstance()->addRetriever(set.impl->err.get());
#endif
    return set;
}
